### ISSUE TITLE
Suggestion: Update a newly selected theme only after a small timeout

### ISSUE THREAD

**Issue by schittli** [kamenminkov/favourite-themes#1]
Hello

thank you very much for sharing your great and useful work!

If we use the Cursor up/down keys in the theme list and navigate fast to next / previous themes, then there are problems with updating / activating the selected theme.

If it is easily doable, it would be ingenious if the theme is updated only after a short timeout of e.g. 500ms:
As long as the user navigates between the themes, the timer would then always be restarted. If the user is idle for e.g. 500ms, then the display is updated.

Thanks a lot, kind regards,
Thomas

**Comment by kamenminkov** [comment]
Yes, I'm aware of that and I've been thinking about how to avoid it - it really becomes a bit laggy if you're going quickly through the list.

**Comment by kamenminkov** [comment]
Just implemented this in `1.6.0` and there's a setting (`favouriteThemes.themeSelectionDelay`) in case you're not happy with the default of 200 ms.
