### ISSUE TITLE
Sometimes, the Dark / Light classification is wrong

### ISSUE THREAD

**Issue by schittli** [kamenminkov/favourite-themes#3]
Hello

Sometimes, favourite-themes detects the from theme type:

![image](https://user-images.githubusercontent.com/8282673/152175311-bcd044e6-c221-4d1c-926f-69342043fd73.png)

Maybe this helps?:
The GitHub Dark High Contrast Source Code is here: https://github.com/primer/github-vscode-theme

Thanks a lot, kind regards,
Thomas

**Comment by kamenminkov** [comment]
Thanks for the tip. Just read through it and noticed that this theme is using `"uiTheme": "hc-black"` (as opposed to the usual `"vs"` or "`vs-dark"`), which is either something that I've missed initially or something that didn't exist back then (more likely I've missed it).

**Comment by kamenminkov** [comment]
Should be fixed in 1.5.0.
